language: python
python:
- 3.6
install:
- pip install -r requirements.txt
before_script:
- export FLASK_ENV="development"
- export FLASK_APP="$TRAVIS_BUILD_DIR/samo-cms/samo"
- mysql -e "CREATE DATABASE samo;"
script:
- pytest -v
services:
- redis-server
- mysql