language: python
python:
- 3.6
cache: pip
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
install:
- pip install -r requirements.txt
env:
  global:
  - MOZ_HEADLESS=1
  - FLASK_ENV="development"
  - FLASK_APP="$TRAVIS_BUILD_DIR/samo-cms/samo"
services:
- redis-server
- mysql
addons:
  firefox: latest
before_script:
- mysql -e "CREATE DATABASE samo;"
- python manage.py initdb
- python run.py &
script:
- pytest -v


