version: '3'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - /home/dev/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${SAMO_DB_PASS}"
      MYSQL_DATABASE: "${SAMO_DB_NAME}"
  redis:
    image: "redis:latest"
  web:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    command: /code/docker/boot.sh
    environment:
      FLASK_ENV: dockertesting
      SAMO_HOST: "${SAMO_HOST}"
      SAMO_PORT: "${SAMO_PORT}"
      SAMO_DB_SERVER: samo-cms_db_1
      SAMO_DB_TYPE: "${SAMO_DB_TYPE}"
      SAMO_DB_NAME: "${SAMO_DB_NAME}"
      SAMO_DB_USER: "${SAMO_DB_USER}"
      SAMO_DB_PASS: "${SAMO_DB_PASS}"
      SAMO_MAIL_SENDGRID_API_KEY: "${SAMO_MAIL_SENDGRID_API_KEY}"
      SAMO_MAIL_DEFAULT_SENDER: "${SAMO_MAIL_DEFAULT_SENDER}"
      SAMO_CELERY_BROKER_URL: redis://samo-cms_redis_1:6379
      SAMO_CELERY_RESULT_BACKEND: redis://samo-cms_redis_1:6379
      SAMO_SECURITY_PASSWORD_SALT: "${SAMO_SECURITY_PASSWORD_SALT}"



    volumes:
    - .:/code
    ports:
    - "8000:5000"
    depends_on:
    - db
    links:
    - redis
  celery:
    build:
      context: ./
      dockerfile: ./docker/celery-worker/Dockerfile
    environment:
      FLASK_ENV: dockertesting
      SAMO_HOST: "${SAMO_HOST}"
      SAMO_PORT: "${SAMO_PORT}"
      SAMO_DB_SERVER: samo-cms_db_1
      SAMO_DB_TYPE: "${SAMO_DB_TYPE}"
      SAMO_DB_NAME: "${SAMO_DB_NAME}"
      SAMO_DB_USER: "${SAMO_DB_USER}"
      SAMO_DB_PASS: "${SAMO_DB_PASS}"
      SAMO_MAIL_SENDGRID_API_KEY: "${SAMO_MAIL_SENDGRID_API_KEY}"
      SAMO_MAIL_DEFAULT_SENDER: "${SAMO_MAIL_DEFAULT_SENDER}"
      SAMO_CELERY_BROKER_URL: redis://samo-cms_redis_1:6379
      SAMO_CELERY_RESULT_BACKEND: redis://samo-cms_redis_1:6379
      SAMO_SECURITY_PASSWORD_SALT: "${SAMO_SECURITY_PASSWORD_SALT}"
    volumes:
    - .:/code
    links:
    - db
    - redis
volumes:
  db-data:


