"""empty message

Revision ID: 5fe69dd22846
Revises: b624a7890119
Create Date: 2018-10-15 00:23:45.659208

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fe69dd22846'
down_revision = 'b624a7890119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.drop_column('comment', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('comment', 'hidden')
    # ### end Alembic commands ###
